TBD54566975/web5-kt

- config/detekt.yml
- credentials/build.gradle.kts
- credentials/src/main/kotlin/SSI.kt
- credentials/src/main/kotlin/model/SSITypes.kt
- credentials/src/test/kotlin/SSITest.kt
implementing presentation exchange
Implementing as seen from here https://identity.foundation/presentation-exchange/#input-descriptor-object 
Created a new function that:
```
/**
* The selectFrom method is a helper function that helps filter out the verifiable credentials which can not be selected and returns
* the selectable credentials.
*
* @param presentationDefinition definition of what is expected in the presentation.
* @param vcJwts verifiable credentials are the credentials from wallet provided to the library to find selectable credentials.
*
* @return the selectable credentials.
*/
@Throws(Exception::class)
private fun selectFrom(presentationDefinition: PresentationDefinitionV2, vcJwts: List<VcJwt>): List<VcJwt> 
```
This is expected to give you all the necessary VCs needed to …
> implementing presentation exchange

- .github/workflows/ci.yml
- README.md
- build.gradle.kts
- credentials/build.gradle.kts
This is an example of how we'll publish things using jitpack.io. This setup follows the one in https://github.com/jitpack/gradle-modular
Jitpack is very simple to set up. And even easier to consume. The README was updated to reflect this. CI also now has a `publishToMavenLocal` task. 
In [jitpack.io](https://jitpack.io/#TBD54566975/web5-sdk-kotlin/) you can see the successful build log. I triggered this build by adding `implementation("com.github.TBD54566975:web5-sdk-kotlin:PR40-SNAPSHOT")` to a local project. 
https://docs.jitpack.io/building/
> Publishing to jitpack

- README.md
- credentials/build.gradle.kts
- credentials/src/main/kotlin/SSI.kt
Code that depends on `web5-sdk-kotlin` currently needs to pull dependencies that are part of public signatures. This PR fixes this. 
For a more details description, see https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
Followed the instructions in a local repository which exercises full functionality.
> Marks some deps as part of the API

- credentials/src/main/kotlin/SSI.kt
- credentials/src/main/kotlin/model/SSITypes.kt
- credentials/src/test/kotlin/SSITest.kt
Adding more tests for pex and adding more robust pex handling
Adding      
`generatePresentationSubmissionFrom(createVpOptions.presentationDefinition, createVpOptions.verifiableCredentialJwts): PresentationSubmission` which does field validation for determining if the VCs provided are valid for the presentation definition.
```
/**
* Validates a list of Verifiable Credentials (VcJwts) against a presentation definition and generates a presentation submission
*
* This method checks the presentation definition and the list of Verifiable Credentials to ensure
* that the required fields in the definition are satisfied by the provided credentials.
*
* Currently, if the presentation definition contains submission requirements, or if any required field in an input
* descriptor is not satisfied by …
```
> updating pex with pres submission

- .github/workflows/ci.yml
- codecov.yaml
Adds a codecov file that splits coverage reports by component. Also splits the upload with the flag to indicate which platform was tested. 
See the codecov comment below. 
* https://docs.codecov.com/docs/flags
* https://docs.codecov.com/docs/components
> Add codecov file and split with flags

- common/src/main/kotlin/web5/sdk/common/Convert.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Crypto.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Ed25519.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Secp256k1.kt
- dids/src/main/kotlin/web5/sdk/dids/DidResolvers.kt
Ensures that `Secp256k1.sign` always returns the low-s signature
> [!NOTE]
> It's **highly unlikely** that AWS KMS or Cloud KMS natively supports guaranteed low-s signatures. Neither KMS' support deterministic k defined in [RFC6979](https://datatracker.ietf.org/doc/html/rfc6979) either. 
> 
> It's worth mentioning that lack of cloud KMS support isn't a deal breaker as the math required to compute low-s from high-s does not require any private key material. However, lack of deterministic-k support may be a deal breaker specifically w.r.t. managing ION update and recovery keys in a cloud KMS if ION requires deterministic signatures
An `ECDSA` signature for a given message and private key is not strictly unique. Specifically, if `(r,s)` is a valid signature, then `(r, mod(-s, n))` is also a …
> Secp256k1 low-s

- dids/src/main/kotlin/web5/sdk/dids/DidIonManager.kt
- dids/src/main/kotlin/web5/sdk/dids/ion/model/Models.kt
- dids/src/test/kotlin/web5/sdk/dids/DidIonTest.kt
Added an option for adding `services` upon DID ION creation. 
This PR:
* Includes validation of the fields as it exists in https://github.com/decentralized-identity/ion-sdk/blob/main/lib/IonRequest.ts#L319.
* Adds tests.
Unit
> Support adding services on DID creation

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
- dids/src/main/kotlin/web5/sdk/dids/DidIonManager.kt
- dids/src/main/kotlin/web5/sdk/dids/ion/model/Models.kt
- dids/src/test/kotlin/web5/sdk/dids/DidIonTest.kt
- dids/src/test/resources/jwkEs256k3Public.json
- docs/examples.md
This PR introduces `recover` and `deactivate` for ion DIDs. Fixes #3 and #2.
Some notes in this PR:
* The `recover` operation API design was so that it matches the `create` API.
* Operations now return an `Ion<operation_type>Result` object. This makes working with DIDs easier.
* Examples were added in the `examples.md` readme.
* Small fixes to ensure the issuance also works with an ION did that was created with an AWS key manager.
* The changes in #87 are merged, as they're needed for tests to pass.
* It's built on top of #77 
Unit tests similar to the ones in the ion-sdk were added.
* https://identity.foundation/sidetree/api/#recover
* https://identity.foundation/sidetree/api/#deactivate
> Support DID Ion Recovery and Deactivate 

- dids/src/main/kotlin/web5/sdk/dids/DidIonManager.kt
- dids/src/test/kotlin/web5/sdk/dids/DidIonTest.kt
- dids/src/test/kotlin/web5/sdk/dids/DidResolversTest.kt
Default did ion sets assertion method used in crypto verification operations
_Describe the tests that you ran to verify your changes. Provide instructions for verification._
> Default ion creation sets assertion method

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
Fix a null pointer that occurs when verifying a VC signed with an ION DID that has no assertionMethod
New unit test added
> Fix null pointer in VC verify

- build.gradle.kts
- credentials/src/test/kotlin/web5/sdk/credentials/StatusListCredentialTest.kt
- crypto/src/main/kotlin/web5/sdk/crypto/InMemoryKeyManager.kt
- crypto/src/test/kotlin/web5/sdk/crypto/Secp256k1Test.kt
- dids/build.gradle.kts
- dids/src/main/kotlin/web5/sdk/dids/DidIonManager.kt
- dids/src/test/kotlin/web5/sdk/dids/DidIonTest.kt
- dids/src/test/kotlin/web5/sdk/dids/DidKeyTest.kt
* replaces `multiformats` libs with handrolled `multihash` function
* the `multiformats` libs necessitate java17 and we need to support java11.
* `multihash` could be more generalized and tossed into common. For now i've left it in `DidIonManager` because that's the only place it's being used
* set java compatibility to 11
> [!NOTE]
> There's a `StatusListCredential` Test that borked after bumping java from 17 down to 11
@nitro-neal 
```
StatusListCredentialTest > should generate StatusListCredential from multiple VerifiableCredentials() FAILED
org.opentest4j.AssertionFailedError: expected: <H4sIAAAAAAAA/2NgQAESAAPT1/8QAAAA> but was: <H4sIAAAAAAAAAGNgQAESAAPT1/8QAAAA>
at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at …
```
> Java 11 compatibility

- dids/src/main/kotlin/web5/sdk/dids/DidDht.kt
- dids/src/test/kotlin/web5/sdk/dids/DidDhtTest.kt
@decentralgabe thoughts on refactoring `isValid` to `validate`? Rationale behind doing so would be:
* some of the function calls used in `isValid` could throw exceptions which means there are two possible outcomes that could occur if a did is invalid. Alternatively we could just try/catch return false in the function. mostly thinking that consistency might be nice
* thinking it may be nice to see why the did is invalid
Created this PR vs. using suggestion in your open PR because it would've ended up being like 3 disjointed suggestions.  Added tests for `validate` as well.
> `did:dht` validate

- .github/workflows/ci.yml
Some of our actions use a version of node that's no longer supported. GitHub is going to force these actions to run on a newer version of node. Took a quick look at the ones flagged in the warning and noticed that there were newer versions. figured we might as well update them directly
> version bump third party actions

- credentials/src/main/kotlin/web5/sdk/credentials/PresentationExchange.kt
- credentials/src/test/kotlin/web5/sdk/credentials/PresentationExchangeTest.kt
- credentials/src/test/resources/pd_filter_array.json
- credentials/src/test/resources/pd_filter_array_multiple_input_descriptors.json
- credentials/src/test/resources/pd_filter_array_single_path.json
- credentials/src/test/resources/pd_mixed_multiple_input_descriptors.json
- credentials/src/test/resources/pd_path_no_filter_dob.json
- credentials/src/test/resources/pd_path_no_filter_multiple_input_descriptors.json
Validates a list of Verifiable Credentials (VCs) against a specified Presentation Definition.
This function ensures that the provided VCs meet the criteria defined in the Presentation Definition.
It first checks for the presence of Submission Requirements in the definition and throws an exception if they exist (not supported
It does this by mapping the input descriptors in the presentation definition to the corresponding VCs. If the number of mapped descriptors does not match the required count, an error is thrown.
More detailed error messages are planned for the future with a Results object that will give warnings, and better details for errors
> Implementing satisfiesPresentationDefinition

- dids/src/main/kotlin/web5/sdk/dids/methods/ion/DidIon.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/jwk/DidJwk.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/key/DidKey.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/web/DidWeb.kt
While we come to consensus on #112 , we're allowing constructors to be public of subclasses of `Did` to be public.
> Allow public constructors for Did subclasses

- credentials/src/main/kotlin/web5/sdk/credentials/PresentationDefinition.kt
I recently used this Kotlin's version of `PresentationDefinition` as a guide to implement the Rust version here: https://github.com/TBD54566975/web5-rs/pull/18
In that PR, there was the [suggestion](https://github.com/TBD54566975/web5-rs/pull/18#discussion_r1409184254) to link directly to the V2 spec, as that's what this class is implementing. Seemed like a good idea!
I'm not going to lie, I was lazy and just copied the comments from here and used them in my Rust code. So I think that suggestion still applies here as well. We're implementing the V2 spec, so linking directly to it seems to make sense!
> update links to v2 spec

- .github/workflows/ci.yml
Fixes #123 by adding a publishing step to buildkite during CI. 
See original issue for motivation. The implementations is the same as in https://github.com/TBD54566975/tbdex-kt/pull/102
The secret `BUILDKITE_ANALYTICS_TOKEN` was set up within the repo.
See https://buildkite.com/organizations/tbd-oss/analytics/suites/web5-kt/runs/7fb7c7ae-6a2a-4099-a49b-15190ce9490c for a sample result.
> Adding test publishing to BuildKite

- .github/workflows/publish.yml
- .gitignore
- README.md
- build.gradle.kts
- common/build.gradle.kts
This PR fixes #68, fixes #126, and fixes #128 by configuring gradle, the repo, and a CI action to publish the libraries from this repo to maven central. 
This PR includes. 
* Updates to the README file on how to import this library, and how to realease it. The current `groupId` we've settled on is `xyz.block`, but that's likely to change (see the convo at https://github.com/TBD54566975/open-source-programs/issues/95). When the time comes, we'll update it. Alternatively, we can delay this PR until that's ready.
* Adding a `publish.yml` file. This workflow will trigger when a new release is cut. It will release the version specified to maven central. See the README updates for more details. 
* Changes to gradle file such that:
* All submodules are included in the root module, importable as …
> Adding publishing to Central Repository using a github action

- testing/module.md
`main` doc publishing was broken due to a missing file.
> Fix docs publishing

- .github/workflows/publish.yml
This PR makes sure that all modules are published to Sonatype. Below, the answer of an AI to the question: what's the difference when running a gradle task prefixed with : , and without the prefix?
> When running a Gradle task, the prefix : is used to specify the project path. The difference between running a task with and without the prefix is as follows:
> 1. Running a task without the prefix: When you run a task without the prefix, Gradle will execute the task in the current project. For example, if you are in the root project directory and run gradle clean, it will execute the clean task in the current project.
> 2. Running a task with the prefix: When you run a task with the prefix :, Gradle will execute the task in the specified project. The prefix : is used to specify the project …
> Fix gradle publishing typo

- README.md
Now that we're confident that our publishing mechanism works (see #156), we can remove all references to jitpack.
This change is doc cleanup only.
> Remove adding dep using jitpack

- .github/workflows/publish.yml
This change updates a step in the publish workflow so that the package in sonatype is released. Once released, it is immutable and available for the worlds to consume. 
Currently, the steps to release include:
1. Cut a release, which published to sonatype staging automatically by running the action https://github.com/TBD54566975/web5-kt/actions/runs/7198920796.
2. Click the "Release" button in https://s01.oss.sonatype.org/#stagingRepositories
This change removes the need of clicking the button in (2).
> Add release to the publishing step

- .github/workflows/ci.yml
The [web5 spec compliance report](https://tbd54566975.github.io/sdk-development/) reports on the status of various features in this SDK. This PR makes sure we rebuild it whenever this repo changes, in case a new feature was added
> trigger sdk-development report build workflow when this repo is merged

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/main/kotlin/web5/sdk/credentials/VerifiablePresentation.kt
- credentials/src/main/kotlin/web5/sdk/credentials/util/JwtUtil.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiablePresentationTest.kt
Add VerifiablePresentation Creation, Signing, and Verification
This provides functionalities to sign, verify, and create presentations, offering a concise API to work with JWT representations of verifiable presentations and ensuring that the signatures and claims within those JWTs can be validated.
Create VP Example:
```
/**
* Create a [VerifiablePresentation] based on the provided parameters.
*
* @param type The type of the presentation, as a [String].
* @param holder The holder URI of the presentation, as a [String].
* @param vcJwts The credentials used in the presentation, as a [String].
* @param additionalData The presentation data, as a generic mapping [Map<String, Any>].
* @return A [VerifiablePresentation] instance.
*
* Example:
* ```
*     val vp = VerifiablePresentation.create(
* …
> Add VerifiablePresentation Creation, Signing, and Verification

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
This PR adds `issuanceDate` and `expirationDate` to the public API when creating VCs.
> Adding options to vc creation

- credentials/src/main/kotlin/web5/sdk/credentials/PresentationExchange.kt
- credentials/src/main/kotlin/web5/sdk/credentials/model/Validator.kt
- credentials/src/test/kotlin/web5/sdk/credentials/PresentationExchangeTest.kt
This method performs several checks to ensure the integrity of the presentation submission model object:
* 1. Ensures that the presentation submission's ID is not empty.
* 2. Validates that the definitionId is not empty.
* 3. Validates descriptorMap is a non-empty list.
* 4. Verifies the input descriptor mapping ids are the same on all levels of nesting.
* 5. Ensures that the path is valid across all levels of nesting
Usage:
```
try {
PresentationExchange.validateSubmission(presentationSubmission)
} catch(Exception e) {
// invalid submission
}
```
web5-spec vector change - https://github.com/TBD54566975/web5-spec/pull/109
> Validate presentaion submission with new validator

- README.md
- build.gradle.kts
- common/build.gradle.kts
- common/src/main/kotlin/web5/sdk/common/ZBase32.kt
- common/src/test/kotlin/web5/sdk/common/ConvertTest.kt
- common/src/test/kotlin/web5/sdk/common/ZBase32Test.kt
- credentials/build.gradle.kts
- crypto/build.gradle.kts
- dids/build.gradle.kts
- removed `crypto` dependency from `common` package
- ignoring tests for ZBase32.encode() and decode() - to be fixed in https://github.com/TBD54566975/web5-kt/issues/221
- bumping all instances of jackson dependencies to be the same `2.14.2`
- wanted to remove the somewhat circular dependency between crypto and common package.
> Remove crypto dependency from common

- crypto/build.gradle.kts
- crypto/src/main/kotlin/web5/sdk/crypto/Secp256k1.kt
- crypto/src/test/kotlin/web5/sdk/crypto/Secp256k1Test.kt
Adding test vectors for Secp256k1
Web5TestVectorsCryptoEs256k
sign()
verify()
Will get checkmarks for kt here:
https://tbd54566975.github.io/sdk-report-runner/
> Adding test vectors for Secp256k1

- README.md
- build.gradle.kts
- common/build.gradle.kts
- credentials/build.gradle.kts
- crypto/build.gradle.kts
- dids/build.gradle.kts
- gradle/libs.versions.toml
Centralizes versions across the `web5-kt` submodules using Gradle Version Catalogs.
Kicking off draft PR now to get early authoritative CI feedback during development.
Addresses:
* #226
> Version Alignment and Introducing Gradle Version Catalogs

- README.md
- build.gradle.kts
- gradle/libs.versions.toml
A series of commits to address security vulns in the `web5-kt` projects. Grouped as one PR so they may be tested together to clear FOSSA security scanning to  ✅. 
On `main`, 5 security issues on FOSSA:
In this PR, 0 security issues on FOSSA:
Recommended merge approach when approved: Rebase, do not squash and merge. This will preserve optionality for us to individually `git blame` and do reverts if necessary.
This PR resolves #240, #242, #243, #244, and adds documentation.
> Suite of Security Vulnerability Fixes

- credentials/src/main/kotlin/web5/sdk/credentials/util/JwtUtil.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiablePresentationTest.kt
- crypto/src/main/kotlin/web5/sdk/crypto/AwsKeyManager.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Crypto.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Dsa.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Ed25519.kt
- crypto/src/main/kotlin/web5/sdk/crypto/InMemoryKeyManager.kt
- crypto/src/main/kotlin/web5/sdk/crypto/KeyGenerator.kt
- crypto/src/main/kotlin/web5/sdk/crypto/KeyManager.kt
- crypto/src/main/kotlin/web5/sdk/crypto/Secp256k1.kt
- crypto/src/test/kotlin/web5/sdk/crypto/AwsKeyManagerTest.kt
- crypto/src/test/kotlin/web5/sdk/crypto/InMemoryKeyManagerTest.kt
- crypto/src/test/kotlin/web5/sdk/crypto/Secp256k1Test.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/dht/DhtClient.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/dht/DidDht.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/ion/DidIon.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/jwk/DidJwk.kt
- dids/src/main/kotlin/web5/sdk/dids/methods/key/DidKey.kt
- dids/src/test/kotlin/web5/sdk/dids/methods/dht/DhtTest.kt
- dids/src/test/kotlin/web5/sdk/dids/methods/dht/DidDhtTest.kt
- dids/src/test/kotlin/web5/sdk/dids/methods/ion/DidIonTest.kt
- dids/src/test/kotlin/web5/sdk/dids/methods/jwk/DidJwkTest.kt
Eliminating use of `Curve` and `Algorithm` from `nimbusds` dependency and instead using our own enums `JwaCurve` and `Jwa`, respectively. Adopting use of `AlgorithmId` which is a combination of `JwaCurve` and `Jwa`. 
This PR is the first step to remove dependency on the nimbusds library and preventing exposing their types through our public API surface.
- Changes to many method signatures in crypto and dids package. Mostly requiring passing in of `AlgorithmId` instead of nimbus Algorithm and nimbus Curve.
- Roll our own enums for JWK as well as various nimbus methods we still use internally, and completely remove nimbusds dependency 
- Unit tests have been fixed to align with the new public API surface. No implementation change happened. 
[JWA …
> Replace usage of nimbusds Algorithm and Curve with our own enums

- dids/src/main/kotlin/web5/sdk/dids/methods/dht/DidDht.kt
fixed `did:dht` resolution.
There was a recent change to `did:dht` TXT record names that requires the method specific id to be included as the last part of each TXT record
`main` is currently looking for several records using strict equality. example [here](https://github.com/TBD54566975/web5-kt/blob/main/dids/src/main/kotlin/web5/sdk/dids/methods/dht/DidDht.kt#L572). 
This PR changes strict equality checks to prefix checks. We would have had to make this change for the root record anyway because of the possibility for `_did.TLD`
> [!WARNING]
> I'll fix create and update in a subsequent PR. want to get this one out to unblock others
> FIX: `did:dht` resolution

- .github/workflows/ci.yml
Now we are only triggering and running the SDK reporting from the Ubuntu run (which is the most traditional build environment).
> Fix duplicated SDK runner trigger

- .github/workflows/gh-pages-deploy.yml
- .github/workflows/publish.yml
The new releases are not being updated as latest because of the `prerelease` tag. This PR fixes it. 
Also fixes #265
> Fix latest releases

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
Add Evidence to our vc data model
Adding optional evidence field to creation of the vc data model
Evidence can be included by an issuer to provide the verifier with additional supporting information in a verifiable credential. This could be used by the verifier to establish the confidence with which it relies on the claims in the verifiable credential.
https://www.w3.org/TR/vc-data-model/#evidence
> Add Evidence

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/test/kotlin/web5/sdk/credentials/PresentationExchangeTest.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
- jose/src/main/kotlin/web5/sdk/jose/jws/Jws.kt
- testing/src/main/kotlin/web5/sdk/testing/TestVectors.kt
Added vcJwt checks to verify
* If any of these steps fail, the function will throw a [IllegalArgumentException] with a message indicating the nature of the failure:
* - exp MUST represent the expirationDate property, encoded as a UNIX timestamp (NumericDate).
* - iss MUST represent the issuer property of a verifiable credential or the holder property of a verifiable presentation.
* - nbf MUST represent issuanceDate, encoded as a UNIX timestamp (NumericDate).
* - jti MUST represent the id property of the verifiable credential or verifiable presentation.
* - sub MUST represent the id property contained in the credentialSubject.
Added new vector - https://github.com/TBD54566975/web5-spec/pull/146
> Make VC Verify more robust

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
Implement Credential Schema
A credential schema defines the structure and content of the data, enabling verifiers to assess if the data adheres to the established schema.
https://www.w3.org/TR/vc-data-model/#data-schemas
* Add CredentialSchema type
* Add optional field to VcCreateOptions
* Update KYC unit test to have latest kyc cred
> Add credential schema

- .github/workflows/ci.yml
Fix build failures due to PRs from external contributors (or bots) which won't have access to artifactory publishing
Example: https://github.com/TBD54566975/web5-kt/actions/runs/9086925778/job/25066223935
> Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project web5: Failed to deploy artifacts: Could not transfer artifact xyz.block:web5-parent:pom:commit-02d5da2-20240516.174542-1 from/to tbd-oss-snapshots (https://blockxyz.jfrog.io/artifactory/tbd-oss-snapshots-maven2): status code: 401, reason phrase:  (401) -> [Help 1]
> Fix artifactory SNAPSHOT publishing w/o credentials

- credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
closes #320 
made `type` nullable when creating a vc via `VerifiableCredential.create()`
i wrote a test that makes sure the vc created with `null` type still has the default type of `VerifiableCredential` and the vcDataModel's `type` array has 1 item `["VerifiableCredential"]`
> making vc type nullable during VerifiableCredential.Create()

- pom.xml
> Issue #323: Enforce jackson-dataformat-cbor to aligned version

- credentials/pom.xml
- credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
- dids/pom.xml
- distribution/pom.xml
- keymanager-aws/pom.xml
- keymanager-aws/src/main/kotlin/web5/sdk/keymanager/aws/AwsKeyManager.kt
- keymanager-aws/src/test/kotlin/web5/sdk/keymanager/aws/AwsKeyManagerTest.kt
- pom.xml
* Note the ⚠️  below and impact on versioning of `web5-kt` this carries via an API change.
* Please do not squash merge this PR; rebase merge is fine. We should preserve 1eb180c258d790822e77742b59d3f209dc7d6b3f so that it may be cleanly reverted as part of #328 
Reviewers, please assess impact of the following changes introduced by this PR:
* Create new module with `artifactId`: `web5-keymanager-aws`
* Add this new module to the `distribution`
* Move `AwsKeyManager` into it, along with `AwsKeyManagerTest`
*  ⚠️ Refactor package name of `AwsKeyManager` from `web5.sdk.crypto` to `web5.sdk.keymanager.aws`. This represents an API change and in strict terms would trigger a major version bump to a `2.x.y` series of `web5-kt` on the next release.
* Remove the `crypto` module dependency on …
> Issue #322: Move AwsKeyManager to its own module

- pom.xml
> dnsjava version bump
