TBD54566975/web5-kt

.github/workflows/gh-pages-deploy.yml
build.gradle.kts

Create nice HTML docs using dokka.
This examples is based on https://github.com/Kotlin/dokka/blob/master/examples/gradle/dokka-multimodule-example/README.md
See the example of what this looks like locally: 
The CI was tested and I was able to see the contents in https://tbd54566975.github.io/web5-sdk-kotlin/docs/htmlMultiModule/index.html
https://kotlinlang.org/docs/dokka-gradle.html

Create nice documentation and publish to GH pages

---

common/src/main/kotlin/Base58.kt
common/src/main/kotlin/Convert.kt
common/src/main/kotlin/Varint.kt
config/detekt.yml
credentials/src/main/kotlin/SSI.kt
credentials/src/main/kotlin/Validation.kt
credentials/src/main/kotlin/model/SSITypes.kt
credentials/src/main/kotlin/utils/XmlSchema112DateUtil.kt
crypto/src/main/kotlin/Main.kt
dids/src/main/kotlin/DidKey.kt

This PR modifies the detekt configuration to check undocumented public functions and classes. All instances that were offending have been fixed as well with the help of Chad.
See above. 
No functional changes.

Add linting for public documentation

---

credentials/src/main/kotlin/SSI.kt

This is a refactor to fix this issue. This will be reworked shortly to make it much more simplified (using json schema approach probably)
Fixes this:
The function generatePresentationSubmissionFrom appears to be too complex based on Cyclomatic Complexity (complexity: 15). Defined complexity threshold for methods is set to '15'

fix cyclomatic-complexity-issue

---

crypto/build.gradle.kts
crypto/src/main/kotlin/web5/sdk/crypto/Secp256k1.kt
crypto/src/test/kotlin/web5/sdk/crypto/Secp256k1Test.kt

Fix some copy + paste bugs in Secp256k1

Fix key type bug in Secp256k1

---

README.md

can be seen [here](https://github.com/TBD54566975/web5-kt/blob/hipster-badges/README.md)

Add hipster badges to README

---

build.gradle.kts

_Include a summary of the change and link to the issue it addresses._
_Include context, motivation, brief description, and an impact of the change(s). List follow-up tasks here._
_Describe the tests that you ran to verify your changes. Provide instructions for verification._

Bump version to 0.0.5

---

.github/workflows/security.yml

- add security scanning to detect vulns
- add license check
- upload report to Github Code Scanning
Fix #119
Fix #120

Add Snyk for Vulns and License checks

---

common/src/main/kotlin/web5/sdk/common/Convert.kt
common/src/test/kotlin/web5/sdk/common/ConvertTest.kt

Added unit tests for `Convert.kt`
Ran unit tests locally and measured coverage. Now getting 98% coverage on Convert.kt

adding tests for Convert class methods

---

credentials/src/main/kotlin/web5/sdk/credentials/PresentationExchange.kt

This is a trivial change so we do less work inside a loop.

JWT and JsonPath parsing done outside the loop

---

dids/src/test/kotlin/web5/sdk/dids/methods/dht/DidDhtTest.kt

Addresses https://github.com/TBD54566975/web5-kt/pull/181#discussion_r1459324710
CC @nitro-neal

Renames a test to comply with convention

---

.github/workflows/codeql.yml

Similar to https://github.com/TBD54566975/tbdex-js/pull/146 -- and no issues were found on this scan for this repo! 😄 
Fix #121

Setup CodeQL SAST

---

.github/workflows/scorecard.yml
README.md

Same as https://github.com/TBD54566975/tbdex-kt/pull/90

Enable OSSF Scorecard

---

README.md

Updating the README's instructions to reflect the current dependencies.
We released a new version of web5-kt, so just updating the README so people could accurately follow the setup. Maybe a GitHub Action where every time we do a release, it updates the README would be helpful.
Doesn't need to be "tested", but I've manually imported these packages on my end

update setup instructions for dependencies

---

credentials/src/main/kotlin/web5/sdk/credentials/util/JwtUtil.kt

resolves - https://github.com/TBD54566975/web5-kt/issues/232

fix jsonwebkey issue

---

credentials/build.gradle.kts
dids/build.gradle.kts

_Include a summary of the change and link to the issue it addresses._
_Include context, motivation, brief description, and an impact of the change(s). List follow-up tasks here._
_Describe the tests that you ran to verify your changes. Provide instructions for verification._

adding temp repo to pull down danubetech deps

---

.github/workflows/ci.yml

Changed `ci.yml` so that `push` triggers only on pushes to main.

changing push trigger to be just for main

---

.github/workflows/ci.yml
.github/workflows/tests-publish.yml

Same as https://github.com/TBD54566975/tbdex-kt/pull/150

Extracts Publish Tests Report Action

---

dids/src/test/kotlin/web5/sdk/dids/methods/web/DidWebTest.kt

Rename the test to match our spec so the runner can pick it up

fix did web test name

---

gradle/libs.versions.toml

Addresses https://github.com/TBD54566975/web5-kt/security/advisories/GHSA-g6qj-pj38-2465

Security Advisory #GHSA-g6qj-pj38-2465: Address CVE-2024-21634

---

.github/workflows/publish.yml
README.md

Similar to https://github.com/TBD54566975/tbdex-kt/pull/188

 Automate GH Release Publication

---

credentials/src/main/kotlin/web5/sdk/credentials/util/JwtUtil.kt
credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
credentials/src/test/kotlin/web5/sdk/credentials/VerifiablePresentationTest.kt

Changed didurl.url to didurl.uri
Also added new unit tests for verifying with did dht over network calls and a full vp flow with did dhts

fix did dht resolve

---

credentials/src/test/kotlin/web5/sdk/credentials/PresentationExchangeTest.kt
credentials/src/test/kotlin/web5/sdk/credentials/VerifiablePresentationTest.kt
jose/src/main/kotlin/web5/sdk/jose/jws/Jws.kt
jose/src/test/kotlin/web5/sdk/jose/jws/JwsTest.kt

Also returning `signerDid` in DecodedJws returned from `Jws.decode(jws, detachedPayload?)`

Extending Jws.decode() to take in optional detachedPayload parameter

---

README.md

Simple `README` change
We added a `jose` submodule, so adding it to list of packages
N/A
Yes

Include jose in README

---

jose/module.md

Add a `module.md` for the `jose` component so it surfaces in the generated API Docs.
New `jose` component, new docs.
N/A

Add module.md for jose

---

common/module.md

Adds a description of the `common` module to the `module.md` used in generating API Docs
As above
N/A

Add description of common to its module.md

---

README.md
credentials/build.gradle.kts

Using block artifactory cache since danubetech is down (again)

using block cache artifactory to pull in danubetech

---

.github/workflows/release.yml

Issue #297: Check out for releases using tbd-releases PAT

---

crypto/pom.xml
crypto/src/main/kotlin/web5/sdk/crypto/jwk/Jwk.kt

Not intended for review, this is a part of a spike to prove out bindings. This PR includes changes to make use of the bindings made available here https://github.com/TBD54566975/web5-rs/pull/138

Spike Jwk bindings

---

crypto/src/main/kotlin/web5/sdk/crypto/Dsa.kt
crypto/src/main/kotlin/web5/sdk/crypto/InMemoryKeyManager.kt
crypto/src/main/kotlin/web5/sdk/crypto/jwk/Jwk.kt

Not intended for review, this is a part of a spike to prove out bindings. This PR includes changes to make use of the bindings made available here https://github.com/TBD54566975/web5-rs/pull/139

Spike InMemoryKeyManager bindings

---

credentials/src/main/kotlin/web5/sdk/credentials/VerifiableCredential.kt
credentials/src/test/kotlin/web5/sdk/credentials/VerifiableCredentialTest.kt
crypto/pom.xml
crypto/src/main/kotlin/web5/sdk/crypto/AwsKeyManager.kt
crypto/src/main/kotlin/web5/sdk/crypto/InMemoryKeyManager.kt
crypto/src/main/kotlin/web5/sdk/crypto/KeyGenerator.kt
crypto/src/main/kotlin/web5/sdk/crypto/KeyManager.kt
dids/src/main/kotlin/web5/sdk/dids/methods/jwk/DidJwk.kt
pom.xml

Not intended for review, this is a part of a spike to prove out retrofitting bindings. This PR includes changes to make use of the bindings made available here https://github.com/TBD54566975/web5-rs/pull/139 and here https://github.com/TBD54566975/web5-rs/pull/140

Add VC signing & verifying binded code

---

README.md

Small README update.
The dependency resolution snipped is missing a closing bracket, breaking the auto-copy/paste pattern.

Update README.md, missing close bracket
